# Generated by Django 6.0.2 on 2026-02-18 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_item_category_iteminstance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Borrow Created'), ('APPROVED', 'Approved by Handler'), ('REJECTED', 'Rejected by Handler'), ('RETURNED', 'Item Returned'), ('MARKED_LATE', 'Marked as Late'), ('MARKED_NOT_RETURNED', 'Marked as Not Returned'), ('STATUS_CHANGED', 'Status Changed'), ('NOTE_ADDED', 'Note Added'), ('DUE_DATE_EXTENDED', 'Due Date Extended')], max_length=30)),
                ('description', models.TextField(help_text='Description of the action')),
                ('metadata', models.JSONField(blank=True, help_text='Additional data like old/new values', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.borrow')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
