# Generated by Django 6.0.2 on 2026-02-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_pending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='requested_role',
            field=models.CharField(choices=[('ADMIN', 'Admin (Management)'), ('HANDLER', 'User Handler'), ('STUDENT', 'Student (Borrower)'), ('PERSONNEL', 'Personnel (Borrower)'), ('USER', 'User (Borrower)')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin (Management)'), ('HANDLER', 'User Handler'), ('STUDENT', 'Student (Borrower)'), ('PERSONNEL', 'Personnel (Borrower)'), ('USER', 'User (Borrower)')], default='USER', max_length=20),
        ),
    ]
