# Generated by Django 6.0.2 on 2026-02-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_requested_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Borrow Created'), ('REQUESTED', 'Borrow Requested'), ('APPROVED', 'Approved by Handler'), ('REJECTED', 'Rejected by Handler'), ('RETURNED', 'Item Returned'), ('MARKED_LATE', 'Marked as Late'), ('MARKED_NOT_RETURNED', 'Marked as Not Returned'), ('STATUS_CHANGED', 'Status Changed'), ('NOTE_ADDED', 'Note Added'), ('DUE_DATE_EXTENDED', 'Due Date Extended')], max_length=30),
        ),
    ]
