from django.urls import path

from .views import (
    approve_registration,
    health_check,
    login,
    me,
    pending_registrations,
    register,
    reject_registration,
    admin_dashboard_stats,
    admin_inventory,
    admin_active_borrows,
    admin_archived_borrows,
    admin_all_borrows,
    admin_borrow_detail,
    admin_reports_analytics,
    admin_ai_recommendations,
    admin_ai_inventory_analysis,
    admin_ai_borrow_analysis,
    admin_ai_custom_analysis,
    admin_categories,
    admin_category_items,
    admin_add_item_instance,
    admin_update_item_instance,
    admin_delete_item_instance,
    admin_create_item,
)

urlpatterns = [
    path("health/", health_check, name="health-check"),
    path("auth/register/", register, name="register"),
    path("auth/login/", login, name="login"),
    path("auth/me/", me, name="me"),
    path("admin/pending/", pending_registrations, name="pending-registrations"),
    path("admin/approve/<int:user_id>/", approve_registration, name="approve-registration"),
    path("admin/reject/<int:user_id>/", reject_registration, name="reject-registration"),
    path("admin/dashboard/stats/", admin_dashboard_stats, name="admin-dashboard-stats"),
    path("admin/inventory/", admin_inventory, name="admin-inventory"),
    path("admin/borrows/active/", admin_active_borrows, name="admin-active-borrows"),
    path("admin/borrows/archived/", admin_archived_borrows, name="admin-archived-borrows"),
    path("admin/borrows/all/", admin_all_borrows, name="admin-all-borrows"),
    path("admin/borrows/<int:borrow_id>/", admin_borrow_detail, name="admin-borrow-detail"),
    path("admin/reports/analytics/", admin_reports_analytics, name="admin-reports-analytics"),
    path("admin/reports/recommendations/", admin_ai_recommendations, name="admin-ai-recommendations"),
    path("admin/ai/inventory-analysis/", admin_ai_inventory_analysis, name="admin-ai-inventory-analysis"),
    path("admin/ai/borrow-analysis/", admin_ai_borrow_analysis, name="admin-ai-borrow-analysis"),
    path("admin/ai/custom-analysis/", admin_ai_custom_analysis, name="admin-ai-custom-analysis"),
    # New inventory management endpoints
    path("admin/categories/", admin_categories, name="admin-categories"),
    path("admin/categories/<int:category_id>/items/", admin_category_items, name="admin-category-items"),
    path("admin/categories/<int:category_id>/items/create/", admin_create_item, name="admin-create-item"),
    path("admin/items/<int:item_id>/instances/add/", admin_add_item_instance, name="admin-add-item-instance"),
    path("admin/item-instances/<int:instance_id>/", admin_update_item_instance, name="admin-update-item-instance"),
    path("admin/item-instances/<int:instance_id>/delete/", admin_delete_item_instance, name="admin-delete-item-instance"),
]
